[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "state-space-filter-comparison"
version = "0.1.0"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
]
[tool.setuptools]
package-dir = {"" = "src"}
